version: '3.4'

services:
  mysqldb:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: hakaru
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
  migratedb:
    image: boxfuse/flyway:latest
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf
    depends_on:
      - mysqldb
    command: migrate
